smartphones:
  min_price: 50
  max_price: 150
  min_discount_pct: 10

notebooks:
  min_price: 500
  max_price: 1500
  min_discount_pct: 15

headphones:
  min_price: 20
  max_price: 200
  min_discount_pct: 5

monitors:
  min_price: 400
  max_price: 1000
  min_discount_pct: 15
